embedding_size: 64
feat_embed_dim: 64
weight_size: [64, 64]
load_batch_size: 2048
learning_rate_scheduler: [0.96, 50]
lambda_coeff: 0.9

cf_model: lightgcn
mess_dropout: [0.1, 0.1]
n_layers: 1
knn_k: 10


reg_weight: [1e-5,1e-3,1e-1]
learning_rate: [0.0001, 0.0005, 0.001, 0.005]

n_ui_layers: 2

layer_times: [1, 2, 4, 8]
dropout_rate: [0.1, 0.3, 0.5, 0.7]
hyper_parameters: ["learning_rate", "reg_weight","layer_times", "dropout_rate"]


